server:
  port: 8080
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:keystore/server_A_keystore.p12
    key-store-password: server_A_keystore
    key-store-type: PKCS12
    key-alias: server-a
    key-store-provider: SUN
    trust-store: classpath:keystore/server_A_keystore.p12
    trust-store-password: server_A_keystore
    trust-store-type: PKCS12