server:
  port: 9090
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:keystore/client.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: client
    key-store-provider: SUN
    trust-store: classpath:keystore/client.p12
    trust-store-password: password
    trust-store-type: PKCS12